export const SET_LOADING = 'setLoading'
export const SET_CHAT = 'setChat'
export const ADD_MESSAGE = 'addMessage'
export const SET_ROOMS = 'setRooms'
export const PUSH_NEW_MESSAGE = 'pushNewMessage'
export const PUSH_ROOM = 'pushRoom'